
import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import com.excilys.ebi.gatling.jdbc.Predef._
import com.excilys.ebi.gatling.http.Headers.Names._
import akka.util.duration._
import bootstrap._
import assertions._

class RecordedSimulation extends Simulation {

	val httpConf = httpConfig
			.baseURL("http://dev:8000")
			.acceptHeader("application/json, text/plain, */*")
			.acceptEncodingHeader("gzip, deflate")
			.acceptLanguageHeader("en-gb,en;q=0.5")
			.authorizationHeader("Basic dGVzdF9pbmQxOnlw")
			.connection("keep-alive")
			.userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:29.0) Gecko/20100101 Firefox/29.0")


	val headers_1 = Map(
			"Cache-Control" -> """no-cache""",
			"Content-Type" -> """application/json;charset=utf-8""",
			"Origin" -> """http://localhost:9000""",
			"Pragma" -> """no-cache"""
	)

	val headers_2 = Map(
			"Cache-Control" -> """max-age=0""",
			"Origin" -> """http://localhost:9000""",
			"yp-language" -> """de"""
	)

	val headers_5 = Map(
			"Origin" -> """http://localhost:9000""",
			"yp-language" -> """de"""
	)

	val headers_8 = Map(
			"Cache-Control" -> """no-cache""",
			"Content-Type" -> """application/json;charset=utf-8""",
			"Origin" -> """http://localhost:9000""",
			"Pragma" -> """no-cache""",
			"yp-language" -> """de"""
	)

	val headers_18 = Map(
			"Content-Type" -> """application/json;charset=utf-8""",
			"Origin" -> """http://localhost:9000""",
			"yp-language" -> """de"""
	)

	val headers_105 = Map(
			"Content-Type" -> """text/plain; charset=UTF-8""",
			"Origin" -> """http://localhost:9000""",
			"yp-language" -> """de"""
	)


	val chain_0 =
		exec(http("request_1")
					.post("/login")
					.headers(headers_1)
						.fileBody("RecordedSimulation_request_1.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(601 milliseconds)
		.exec(http("request_2")
					.get("/activityoffers")
					.headers(headers_2)
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(378 milliseconds)
		.exec(http("request_3")
					.get("//coachmessages")
					.headers(headers_2)
					.queryParam("""uistate""", """select.content""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(56 milliseconds)
		.exec(http("request_4")
					.get("/notifications")
					.headers(headers_2)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(48)
		.exec(http("request_5")
					.get("/activityoffers")
					.headers(headers_5)
					.queryParam("""activity""", """5278c6adcdeab69a25000037""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(282 milliseconds)
		.exec(http("request_6")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """schedule.offer""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_7")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_8")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_8.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(608 milliseconds)
		.exec(http("request_9")
					.post("/activityplans")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_9.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(107 milliseconds)
		.exec(http("request_10")
					.get("/activityplans/5398421e2455ea65ea20cfe2")
					.headers(headers_5)
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(344 milliseconds)
		.exec(http("request_11")
					.get("/activityplans/5398421e2455ea65ea20cfe2")
					.headers(headers_5)
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(590 milliseconds)
		.exec(http("request_12")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_12.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(212 milliseconds)
		.exec(http("request_13")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_13.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(306 milliseconds)
		.exec(http("request_14")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_14.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(289 milliseconds)
		.exec(http("request_15")
					.get("/activityoffers")
					.headers(headers_5)
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(161 milliseconds)
		.exec(http("request_16")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """select.content""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_17")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(3)
		.exec(http("request_18")
					.put("/profiles/5303721a4dba580000000016")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_18.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_19")
					.get("/activityoffers")
					.headers(headers_5)
					.queryParam("""activity""", """5332a3290f9b32255d24897d""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(227 milliseconds)
		.exec(http("request_20")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """schedule.offer""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_21")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(925 milliseconds)
		.exec(http("request_22")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_22.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(888 milliseconds)
		.exec(http("request_23")
					.post("/activityplans")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_23.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(128 milliseconds)
		.exec(http("request_24")
					.get("/activityplans/539842282455ea65ea20cfe5")
					.headers(headers_5)
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(278 milliseconds)
		.exec(http("request_25")
					.get("/activityplans/539842282455ea65ea20cfe5")
					.headers(headers_5)
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(622 milliseconds)
		.exec(http("request_26")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_26.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(199 milliseconds)
		.exec(http("request_27")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_27.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(82 milliseconds)
		.exec(http("request_28")
					.get("/activityoffers")
					.headers(headers_5)
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(170 milliseconds)
		.exec(http("request_29")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """select.content""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_30")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(89 milliseconds)
		.exec(http("request_31")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_31.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(4)
		.exec(http("request_32")
					.get("/assessments/525faf0ac558d40000000005/results/newest")
					.headers(headers_5)
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_33")
					.get("/assessments/525faf0ac558d40000000005")
					.headers(headers_5)
					.queryParam("""populate""", """questions""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(437 milliseconds)
		.exec(http("request_34")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """check.content""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_35")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(4)
		.exec(http("request_36")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000dd")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_36.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(814 milliseconds)
		.exec(http("request_37")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000dc")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_37.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(969 milliseconds)
		.exec(http("request_38")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000dc")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_38.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_39")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000da")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_39.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_40")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000da")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_40.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_41")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000d7")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_41.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(4)
		.exec(http("request_42")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000d1")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_42.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(924 milliseconds)
		.exec(http("request_43")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000d1")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_43.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(136 milliseconds)
		.exec(http("request_44")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000d0")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_44.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(941 milliseconds)
		.exec(http("request_45")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000d0")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_45.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_46")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000d0")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_46.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(767 milliseconds)
		.exec(http("request_47")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000cf")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_47.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(2)
		.exec(http("request_48")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000ce")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_48.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(943 milliseconds)
		.exec(http("request_49")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000ce")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_49.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(991 milliseconds)
		.exec(http("request_50")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000ce")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_50.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(3)
		.exec(http("request_51")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000cc")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_51.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(900 milliseconds)
		.exec(http("request_52")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000cc")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_52.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(135 milliseconds)
		.exec(http("request_53")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000cb")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_53.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(989 milliseconds)
	val chain_1 =
		exec(http("request_54")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000ca")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_54.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(18 milliseconds)
		.exec(http("request_55")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000cb")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_55.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(716 milliseconds)
		.exec(http("request_56")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c9")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_56.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(925 milliseconds)
		.exec(http("request_57")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c9")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_57.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(560 milliseconds)
		.exec(http("request_58")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c8")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_58.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(923 milliseconds)
		.exec(http("request_59")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c8")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_59.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(3)
		.exec(http("request_60")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c6")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_60.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(915 milliseconds)
		.exec(http("request_61")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c5")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_61.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(37 milliseconds)
		.exec(http("request_62")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c6")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_62.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(807 milliseconds)
		.exec(http("request_63")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c4")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_63.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(953 milliseconds)
		.exec(http("request_64")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c4")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_64.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(711 milliseconds)
		.exec(http("request_65")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c3")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_65.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(921 milliseconds)
		.exec(http("request_66")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c3")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_66.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(318 milliseconds)
		.exec(http("request_67")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c2")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_67.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(920 milliseconds)
		.exec(http("request_68")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c2")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_68.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(406 milliseconds)
		.exec(http("request_69")
					.put("/assessments/525faf0ac558d40000000005/answers/5278c51a6166f2de240000c1")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_69.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_70")
					.get("/assessments/525faf0ac558d40000000005/results/newest")
					.headers(headers_5)
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(50 milliseconds)
		.exec(http("request_71")
					.get("/assessments/525faf0ac558d40000000005/results/newest")
					.headers(headers_5)
					.queryParam("""populatedeep""", """answers.question""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(213 milliseconds)
		.exec(http("request_72")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """focus.content""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_73")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(2)
		.exec(http("request_74")
					.put("/profiles/5303721a4dba580000000016")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_74.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_75")
					.get("/assessments/525faf0ac558d40000000005/results/newest")
					.headers(headers_5)
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(387 milliseconds)
		.exec(http("request_76")
					.post("/assessments/525faf0ac558d40000000005/results")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_76.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(568 milliseconds)
		.exec(http("request_77")
					.get("/assessments/525faf0ac558d40000000005/results/newest")
					.headers(headers_5)
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_78")
					.put("/profiles/5303721a4dba580000000016")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_78.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(309 milliseconds)
		.exec(http("request_79")
					.post("/assessments/525faf0ac558d40000000005/results")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_79.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_80")
					.get("/activityoffers")
					.headers(headers_5)
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(202 milliseconds)
		.exec(http("request_81")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """select.content""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_82")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(2)
		.exec(http("request_83")
					.get("/activityoffers")
					.headers(headers_5)
					.queryParam("""activity""", """5278c6accdeab69a2500000b""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(274 milliseconds)
		.exec(http("request_84")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """schedule.offer""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_85")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(939 milliseconds)
		.exec(http("request_86")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_86.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_87")
					.post("/activityplans")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_87.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(150 milliseconds)
		.exec(http("request_88")
					.get("/activityplans/539842632455ea65ea20d071")
					.headers(headers_5)
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(284 milliseconds)
		.exec(http("request_89")
					.get("/activityplans/539842632455ea65ea20d071")
					.headers(headers_5)
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(592 milliseconds)
		.exec(http("request_90")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_90.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(229 milliseconds)
		.exec(http("request_91")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_91.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(261 milliseconds)
		.exec(http("request_92")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_92.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_93")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_93.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(255 milliseconds)
		.exec(http("request_94")
					.put("/activityplans/539842632455ea65ea20d071")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_94.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_95")
					.get("/activityoffers")
					.headers(headers_5)
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(211 milliseconds)
		.exec(http("request_96")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """select.content""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_97")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_98")
					.get("/activityoffers")
					.headers(headers_5)
					.queryParam("""activity""", """5278c6adcdeab69a2500003e""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(220 milliseconds)
		.exec(http("request_99")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """schedule.offer""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(27 milliseconds)
		.exec(http("request_100")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(733 milliseconds)
		.exec(http("request_101")
					.post("/activityplans")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_101.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(114 milliseconds)
		.exec(http("request_102")
					.get("/activityplans/5398426b2455ea65ea20d092")
					.headers(headers_5)
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(222 milliseconds)
		.exec(http("request_103")
					.get("/activityplans/5398426b2455ea65ea20d092")
					.headers(headers_5)
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(704 milliseconds)
		.exec(http("request_104")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_104.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(98 milliseconds)
		.exec(http("request_105")
					.delete("/activityplans/5398426b2455ea65ea20d092")
					.headers(headers_105)
						.fileBody("RecordedSimulation_request_105.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(350 milliseconds)
		.exec(http("request_106")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_106.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(20 milliseconds)
	val chain_2 =
		exec(http("request_107")
					.get("/activityoffers")
					.headers(headers_5)
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_108")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_108.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(231 milliseconds)
		.exec(http("request_109")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """select.content""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_110")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(3)
		.exec(http("request_111")
					.get("/activityplans")
					.headers(headers_5)
					.queryParam("""filter[status]""", """active""")
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(316 milliseconds)
		.exec(http("request_112")
					.post("/error")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_112.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(115 milliseconds)
		.exec(http("request_113")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """plan.offer""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_114")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_115")
					.get("/diaryentries")
					.headers(headers_5)
					.queryParam("""populate""", """activityPlan""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(256 milliseconds)
		.exec(http("request_116")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """diary.content""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_117")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(3)
		.exec(http("request_118")
					.post("/diaryentries")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_118.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(94 milliseconds)
		.exec(http("request_119")
					.put("/profiles/5303721a4dba580000000016")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_119.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_120")
					.get("/activityplans")
					.headers(headers_5)
					.queryParam("""filter[status]""", """active""")
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(370 milliseconds)
		.exec(http("request_121")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """plan.offer""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_122")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(3)
		.exec(http("request_123")
					.post("/error")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_123.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(122 milliseconds)
		.exec(http("request_124")
					.put("/activityplans/539720dad3f56b9ee3a90c76/events/539720dad3f56b9ee3a90c79")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_124.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(130 milliseconds)
		.exec(http("request_125")
					.get("/activityplans/539720dad3f56b9ee3a90c76")
					.headers(headers_5)
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(420 milliseconds)
		.exec(http("request_126")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """schedule.plan""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_127")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(756 milliseconds)
		.exec(http("request_128")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_128.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(2)
		.exec(http("request_129")
					.put("/activityplans/539720dad3f56b9ee3a90c76/events/539720dad3f56b9ee3a90c79")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_129.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_130")
					.put("/activityplans/539720dad3f56b9ee3a90c76/events/539720dad3f56b9ee3a90c79")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_130.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(489 milliseconds)
		.exec(http("request_131")
					.get("/activityplans")
					.headers(headers_5)
					.queryParam("""filter[status]""", """active""")
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(509 milliseconds)
		.exec(http("request_132")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """plan.offer""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_133")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(1)
		.exec(http("request_134")
					.get("/activityplans/539842282455ea65ea20cfe5")
					.headers(headers_5)
					.queryParam("""populate""", """owner""")
					.queryParam("""populate""", """invitedBy""")
					.queryParam("""populate""", """joiningUsers""")
					.queryParam("""populate""", """activity""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(431 milliseconds)
		.exec(http("request_135")
					.get("//coachmessages")
					.headers(headers_5)
					.queryParam("""uistate""", """schedule.plan""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.exec(http("request_136")
					.get("/notifications")
					.headers(headers_5)
					.queryParam("""sort""", """created:-1""")
					.queryParam("""populate""", """author""")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(760 milliseconds)
		.exec(http("request_137")
					.post("/activityplans/conflicts")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_137.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(383 milliseconds)
		.exec(http("request_138")
					.post("/error")
					.headers(headers_8)
						.fileBody("RecordedSimulation_request_138.txt")
					.basicAuth("""test_ind1""","""yp""")
			)
		.pause(8)
		.exec(http("request_139")
					.put("/activityplans/539842282455ea65ea20cfe5")
					.headers(headers_18)
						.fileBody("RecordedSimulation_request_139.txt")
					.basicAuth("""test_ind1""","""yp""")
			)

	val scn = scenario("Scenario Name")
		.exec(
			chain_0,			chain_1,			chain_2		)

	setUp(scn.users(100).protocolConfig(httpConf))
}